### ISSUE TITLE
Use sbt instead of activator

### ISSUE THREAD

**Issue by benmccann** [rossma/pizarra-beta#4]
activator is deprecated. It would be good to delete the `bin` and `libexec` directories and replace references to activator in the readme with sbt

**Comment by rossma** [comment]
Thanks, I am probably not going to do anymore work on this project as it was just a playground app for me. Since doing this I am feeling Play is too much for what I need from it. I want to do an AKKA-HTTP playground app with Vue. So maybe will get around to that soon
